club:
  files:
    directory: /home/site/filesqa
  site:
    domain: http://qa.republic-club.by
server:
  port: 28011
spring:
  liquibase:
    contexts: qa
  datasource:
    database: afishaqa
debug: true