spring:
  datasource:
    database: afisha
    url: jdbc:mariadb://127.0.0.1:3306/${spring.datasource.database}?characterEncoding=UTF-8&autoReconnect=true&useSSL=false&useUnicode=true
    username: afisha
    password: afishapass
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
      show_sql: true
  liquibase:
    contexts: dev
  servlet:
    multipart:
      max-file-size: 128MB
      max-request-size: 128MB
  thymeleaf:
    enabled: true
  main:
    allow-bean-definition-overriding: true
server:
  port: 28010
log4j:
  logger:
    org:
      hibernate:
        SQL: debug
        type: trace
club:
  files:
    directory: /tmp
  site:
    email:
      admin: spam@republic-club.by
mail:
  host: smtp.yandex.ru
  port: 587
  protocol: smtp
  default-encoding: UTF-8
  username: spam@republic-club.by
  password: secretpassword

bepaid:
  payment:
    test: true
    store:
      id: 363
      key: 4f585d2709776e53d080f36872fd1b63b700733e7624dfcadd057296daa37df6

net:
  sf:
    jasperreports:
      default:
        font:
          name: Serif
          size: 12
        pdf:
          font:
            name: Serif
            encoding: utf8
            embedded: false
