debug: true
club:
  site:
    domain: http://localhost
datasource:
  database: afisha
  driver-class-name: org.h2.Driver
  url: jdbc:h2:mem:${datasource.database};DB_CLOSE_DELAY=-1
  username: sa
  password: sa