spring:
  liquibase:
    contexts: integration-test
    drop-first: true
    change-log: classpath:db/changelog/db.changelog-master-integration-test.yaml
debug: true
club:
  site:
    domain: http://localhost
datasource:
  driver-class-name: org.h2.Driver
  url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
  username: sa
  password: sa